bottleneck_size: 25
add_cross_attention: False
exp_name: DoQAsep_coqa_baseline
epoches: 10
weight_decay: 0.0
learning_rate: 0.00005
warmup_steps: 1000
adam_epsilon: 1.0e-12
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 3
gradient_accumulation_steps: 16
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 4
fp16: false
max_grad_norm: 1.0
logging_steps: 1000
save_steps: 1000
output_dir: ../CQAModel/CoQA/Bert_baseline/sep-dev-in_training
evaluate_during_training: True
version_2_with_negative: True
verbose_logging: True
max_answer_length: 40
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: ../preprocessing_files/bert/CoQA/train_clean_truncated
eval_feature_file: ../preprocessing_files/bert/CoQA/dev_clean_truncated
eval_json: ../dataset_local/coqa/coqa-dev-v1.0.json

model: BERTQA_coqa
pretrained_name: bert-base-uncased
pretrained_tokenizer: BertTokenizer

model_config:
  pos_att_type: "c2p|p2c"
  relative_attention: False
  max_relative_positions: 10
