bottleneck_size: 24
add_cross_attention: false
exp_name: CoQA_bert_base_uncased_noq
epoches: 3
weight_decay: 0.0
learning_rate: 0.00003
warmup_steps: 1000
adam_epsilon: 1.0e-6
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 6
gradient_accumulation_steps: 4
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 2
fp16: False
max_grad_norm: 10.0
logging_steps: 1000
save_steps: 1000
output_dir: ../CQAModel/CoQA/BERT_noq/
evaluate_during_training: True
version_2_with_negative: True
verbose_logging: True
max_answer_length: 17
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: ../preprocessing_files/bert/CoQA/clean_base_train_file_HAE
eval_feature_file: ../preprocessing_files/bert/CoQA/clean_base_dev_file_HAE
eval_json: ../dataset_local/CoQA/coqa-dev-v1.0.json

model: BERTQA_original_coqa
pretrained_name: bert-base-uncased
pretrained_tokenizer: BertTokenizer


model_config:
  pos_att_type: "c2p|p2c"
  relative_attention: False
  max_relative_positions: 10
