saved_directory: ../../bigdata/CQAModel/currentQ-dev-in_training-roberta_no_rel_att
checkpoint_step: 1350
eval_file: roberta/current_doqa/doqa_test_file_cooking
exp_name: eval_cooking_result_current-roberta_no_rel_att