saved_directory: ../CQAModel/CoQA/Bert-HF/
eval_file: ../preprocessing_files/bert/CoQA/diff_decoding/clean_base_dev_file_HAE
eval_json: ../dataset_local/coqa/coqa-dev-v1.0.json
exp_name: eval_hf_bert_CoQA
beam_search: 1