hidden_size: 768
max_relative_positions: 10
exp_name: DoQA_All_SEP
epoches: 30
weight_decay: 0.01
learning_rate: 0.00005
warmup_steps: 500
adam_epsilon: 0.000000000001
batch_size: 3
gradient_accumulation_steps: 16
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 2
fp16: False
max_grad_norm: 1.0
logging_steps: 50
save_steps: 50
output_dir: ../../bigdata/CQAModel/all_sep_dev_in_training_no_rel_att
evaluate_during_training: True
version_2_with_negative: False
verbose_logging: True
max_answer_length: 40
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: all_sep_doqa/doqa_train_file_cooking
eval_feature_file: all_sep_doqa/doqa_dev_file_cooking
