hidden_size: 768
max_relative_positions: 10
exp_name: CustomModel_train
epoches: 30
weight_decay: 0.01
learning_rate: 0.00005
warmup_steps: 500
adam_epsilon: 0.000000000001
batch_size: 24
gradient_accumulation_steps: 4
local_rank: -1
seed: 42
num_labels: 2

q_config: 
  n_layer: 3
  layer_norm_eps: 0.000000000001
  intermediate_size: 3072
  hidden_size: 768
  num_attention_heads: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  pos_att_type: c2p|p2c
  relative_attention: True
  max_relative_positions: 10
  dropout: 0.1
p_config: 
  n_layer: 3
  layer_norm_eps: 0.000000000001
  hidden_size: 768
  intermediate_size: 3072
  num_attention_heads: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  pos_att_type: c2p|p2c
  relative_attention: True
  max_relative_positions: 10
  dropout: 0.1
r_config: 
  n_layer: 3
  layer_norm_eps: 0.000000000001
  intermediate_size: 3072
  hidden_size: 768
  num_attention_heads: 12
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  pos_att_type: c2p|p2c
  relative_attention: True
  max_relative_positions: 10
  dropout: 0.1