bottleneck_size: 16
add_cross_attention: False
exp_name: DoQAsep_hf_bert_base_uncased_bottleneck_16_vh_011th_shared
epoches: 20
weight_decay: 0.0
learning_rate: 0.00005
warmup_steps: 500
adam_epsilon: 1.0e-12
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 3
gradient_accumulation_steps: 16
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 2
fp16: False
max_grad_norm: 1.0
logging_steps: 50
save_steps: 50
output_dir: ../CQAModel/DoQA/Bert-base-HF_16/sep-dev-in_training
evaluate_during_training: True
version_2_with_negative: True
verbose_logging: True
max_answer_length: 40
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: ../preprocessing_files/devsplit_in_train/bert/sep_doqa/doqa_train_file_cooking
# dev_feature_file: ../preprocessing_files/devsplit_in_train/bert/sep_doqa/doqa_train_file_cooking
eval_feature_file: ../preprocessing_files/devsplit_in_train/bert/sep_doqa/doqa_dev_file_cooking

model: BERTQA_memory3
pretrained_name: bert-base-uncased

model_config:
  pos_att_type: "c2p|p2c"
  relative_attention: False
  max_relative_positions: 10
