#!/user/bin/shell
python extract_feature_bert_doqa_different_decode.py --config preprocessing_configs/bert/DoQA/diff_decoding/bert_test_doqa_cooking_HAE.yaml
python extract_feature_bert_doqa_different_decode.py --config preprocessing_configs/bert/DoQA/diff_decoding/bert_test_doqa_movies_HAE.yaml
python extract_feature_bert_doqa_different_decode.py --config preprocessing_configs/bert/DoQA/diff_decoding/bert_test_doqa_travel_HAE.yaml

