#!/user/bin/shell
python extract_feature_bert_quac_truncated_past.py --config preprocessing_configs/bert/QuAC/base_dev_truncated_HAE_past.yaml
python extract_feature_bert_quac_truncated_past.py --config preprocessing_configs/bert/QuAC/base_train_truncated_HAE_past.yaml