saved_directory: ../CQAModel/DoQA/BERT_noq/
eval_file: ../preprocessing_files/bert/DoQA/base_test_file_cooking_HAE
eval_json: ../dataset_local/DoQA/doqa_dataset/doqa-cooking-test-v2.1.json
exp_name: eval_bert_cooking_noq