saved_directory: ../CQAModel/DoQA/Roberta-base-HF_16/sep-dev-in_training
eval_file: ../preprocessing_files/devsplit_in_train/roberta/sep_doqa/doqa_test_file_cooking
exp_name: eval_hf_roberta_base_cooking