bottleneck_size: 16
add_cross_attention: false
exp_name: DoQAsep_hf_bart_large_uncased_bottleneck_quac_bs
epoches: 10
weight_decay: 0.0
learning_rate: 0.00005
warmup_steps: 5000
adam_epsilon: 1.0e-12
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 1
gradient_accumulation_steps: 1
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 2
fp16: False
max_grad_norm: 1.0
logging_steps: 10
save_steps: 10
output_dir: ../CQAModel/QuAC/Bart-base/sep-dev-in_training
evaluate_during_training: True
version_2_with_negative: True
verbose_logging: True
max_answer_length: 30
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: ../preprocessing_files/bart/QuAC/base_pytest
eval_feature_file: ../preprocessing_files/bart/QuAC/base_pytest
eval_json: ../dataset_local/quac/val_v0.2.json

model: BARTQA
pretrained_name: facebook/bart-base
pretrained_tokenizer: BartTokenizer


model_config:
  pos_att_type: "c2p|p2c"
  relative_attention: False
  max_relative_positions: 10
