epoches: 80
weight_decay: 0.01
adam_epsilon: 0.000000000001
warmup_steps: 500
learning_rate: 0.00005
gradient_accumulation_steps: 4
batch_size: 10
local_rank: -1
fp16: False
max_grad_norm: 1.0
evaluate_during_training: True
version_2_with_negative: False
logging_steps: 1000
save_steps: 1000
max_answer_length: 30
do_lower_case: True
verbose_logging: True
null_score_diff_threshold: 0.0
n_best_size: 20
output_dir: doqa_save_model_validation
exp_name: DoQA_BertBaseline_validation
seed: 42
