bottleneck_size: 1
exp_name: DoQAsep_albert_base_v2
epoches: 20
weight_decay: 0.01
learning_rate: 0.0001
warmup_steps: 500
adam_epsilon: 1.0e-12
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 3
gradient_accumulation_steps: 16
local_rank: -1
seed: 42
num_labels: 2
dialog_labels: 2
fp16: False
max_grad_norm: 1.0
logging_steps: 50
save_steps: 50
output_dir: ../CQAModel/DoQA/Albert-base-v2/sep-dev-in_training
evaluate_during_training: True
version_2_with_negative: False
verbose_logging: True
max_answer_length: 40
n_best_size: 20
null_score_diff_threshold: 0.0
do_lower_case: True
train_feature_file: albert/sep_doqa/doqa_train_file_cooking
eval_feature_file: albert/sep_doqa/doqa_dev_file_cooking

model: ALBERTQA
pretrained_name: albert-base-v2

model_config:
  pos_att_type: "c2p|p2c"
  relative_attention: false
  max_relative_positions: 10
